"""New data model to support new content model

Revision ID: 09ccd347175f
Revises: 
Create Date: 2019-11-10 19:08:31.289924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ccd347175f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('node_version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=140), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_content_version'), 'article', ['content_version'], unique=False)
    op.create_index(op.f('ix_article_node_id'), 'article', ['node_id'], unique=False)
    op.create_index(op.f('ix_article_node_version'), 'article', ['node_version'], unique=False)
    op.create_table('article_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('node_version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=140), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_revision_content_version'), 'article_revision', ['content_version'], unique=False)
    op.create_index(op.f('ix_article_revision_node_id'), 'article_revision', ['node_id'], unique=False)
    op.create_index(op.f('ix_article_revision_node_version'), 'article_revision', ['node_version'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('roles', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_node_id'), 'user', ['node_id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_version'), 'user', ['version'], unique=False)
    op.create_table('user_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('roles', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_revision_email'), 'user_revision', ['email'], unique=True)
    op.create_index(op.f('ix_user_revision_node_id'), 'user_revision', ['node_id'], unique=True)
    op.create_index(op.f('ix_user_revision_username'), 'user_revision', ['username'], unique=True)
    op.create_index(op.f('ix_user_revision_version'), 'user_revision', ['version'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_history', sa.UnicodeText(), nullable=True),
    sa.Column('tags', sa.UnicodeText(), nullable=True),
    sa.Column('_parents', sa.UnicodeText(), nullable=True),
    sa.Column('_children', sa.UnicodeText(), nullable=True),
    sa.Column('first_child', sa.Integer(), nullable=True),
    sa.Column('next_node', sa.Integer(), nullable=True),
    sa.Column('last_node', sa.Integer(), nullable=True),
    sa.Column('sticky', sa.Boolean(), nullable=True),
    sa.Column('anchor', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_child')
    )
    op.create_index(op.f('ix_node_tags'), 'node', ['tags'], unique=False)
    op.create_index(op.f('ix_node_timestamp'), 'node', ['timestamp'], unique=False)
    op.create_index(op.f('ix_node_version'), 'node', ['version'], unique=False)
    op.create_table('node_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_history', sa.UnicodeText(), nullable=True),
    sa.Column('tags', sa.UnicodeText(), nullable=True),
    sa.Column('_parents', sa.UnicodeText(), nullable=True),
    sa.Column('_children', sa.UnicodeText(), nullable=True),
    sa.Column('first_child', sa.Integer(), nullable=True),
    sa.Column('next_node', sa.Integer(), nullable=True),
    sa.Column('last_node', sa.Integer(), nullable=True),
    sa.Column('sticky', sa.Boolean(), nullable=True),
    sa.Column('anchor', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_child')
    )
    op.create_index(op.f('ix_node_revision_tags'), 'node_revision', ['tags'], unique=False)
    op.create_index(op.f('ix_node_revision_timestamp'), 'node_revision', ['timestamp'], unique=False)
    op.create_index(op.f('ix_node_revision_version'), 'node_revision', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_revision_version'), table_name='node_revision')
    op.drop_index(op.f('ix_node_revision_timestamp'), table_name='node_revision')
    op.drop_index(op.f('ix_node_revision_tags'), table_name='node_revision')
    op.drop_table('node_revision')
    op.drop_index(op.f('ix_node_version'), table_name='node')
    op.drop_index(op.f('ix_node_timestamp'), table_name='node')
    op.drop_index(op.f('ix_node_tags'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_user_revision_version'), table_name='user_revision')
    op.drop_index(op.f('ix_user_revision_username'), table_name='user_revision')
    op.drop_index(op.f('ix_user_revision_node_id'), table_name='user_revision')
    op.drop_index(op.f('ix_user_revision_email'), table_name='user_revision')
    op.drop_table('user_revision')
    op.drop_index(op.f('ix_user_version'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_node_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_article_revision_node_version'), table_name='article_revision')
    op.drop_index(op.f('ix_article_revision_node_id'), table_name='article_revision')
    op.drop_index(op.f('ix_article_revision_content_version'), table_name='article_revision')
    op.drop_table('article_revision')
    op.drop_index(op.f('ix_article_node_version'), table_name='article')
    op.drop_index(op.f('ix_article_node_id'), table_name='article')
    op.drop_index(op.f('ix_article_content_version'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
