"""Working through site requirements

Revision ID: a82c96ee9fa7
Revises: 
Create Date: 2020-01-11 08:06:53.910701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82c96ee9fa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_version', sa.Integer(), nullable=True),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_article__id'), 'article', ['_id'], unique=False)
    op.create_index(op.f('ix_article__node_id'), 'article', ['_node_id'], unique=False)
    op.create_index(op.f('ix_article__timestamp'), 'article', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_article__version'), 'article', ['_version'], unique=False)
    op.create_table('article_revision',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('_id', '_version')
    )
    op.create_index(op.f('ix_article_revision__id'), 'article_revision', ['_id'], unique=False)
    op.create_index(op.f('ix_article_revision__node_id'), 'article_revision', ['_node_id'], unique=False)
    op.create_index(op.f('ix_article_revision__timestamp'), 'article_revision', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_article_revision__version'), 'article_revision', ['_version'], unique=False)
    op.create_table('content_type',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_version', sa.Integer(), nullable=True),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('content_class', sa.String(length=200), nullable=True),
    sa.Column('editable_fields', sa.UnicodeText(), nullable=True),
    sa.Column('viewable_fields', sa.UnicodeText(), nullable=True),
    sa.Column('edit_url', sa.String(length=100), nullable=True),
    sa.Column('view_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_content_type__id'), 'content_type', ['_id'], unique=False)
    op.create_index(op.f('ix_content_type__node_id'), 'content_type', ['_node_id'], unique=False)
    op.create_index(op.f('ix_content_type__timestamp'), 'content_type', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_content_type__version'), 'content_type', ['_version'], unique=False)
    op.create_index(op.f('ix_content_type_name'), 'content_type', ['name'], unique=False)
    op.create_table('content_type_revision',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('content_class', sa.String(length=200), nullable=True),
    sa.Column('editable_fields', sa.UnicodeText(), nullable=True),
    sa.Column('viewable_fields', sa.UnicodeText(), nullable=True),
    sa.Column('edit_url', sa.String(length=100), nullable=True),
    sa.Column('view_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('_id', '_version')
    )
    op.create_index(op.f('ix_content_type_revision__id'), 'content_type_revision', ['_id'], unique=False)
    op.create_index(op.f('ix_content_type_revision__node_id'), 'content_type_revision', ['_node_id'], unique=False)
    op.create_index(op.f('ix_content_type_revision__timestamp'), 'content_type_revision', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_content_type_revision__version'), 'content_type_revision', ['_version'], unique=False)
    op.create_index(op.f('ix_content_type_revision_name'), 'content_type_revision', ['name'], unique=False)
    op.create_table('site',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_version', sa.Integer(), nullable=True),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('site_name', sa.String(length=200), nullable=True),
    sa.Column('environment_name', sa.String(length=200), nullable=True),
    sa.Column('last_published', sa.DateTime(), nullable=True),
    sa.Column('local_build_dir', sa.String(length=200), nullable=True),
    sa.Column('static_files_dir', sa.String(length=200), nullable=True),
    sa.Column('hosting_type', sa.String(length=100), nullable=True),
    sa.Column('content_hash', sa.String(length=200), nullable=True),
    sa.Column('index_content', sa.Integer(), nullable=True),
    sa.Column('menu_content', sa.UnicodeText(), nullable=True),
    sa.Column('groups_content', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_site__id'), 'site', ['_id'], unique=False)
    op.create_index(op.f('ix_site__node_id'), 'site', ['_node_id'], unique=False)
    op.create_index(op.f('ix_site__timestamp'), 'site', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_site__version'), 'site', ['_version'], unique=False)
    op.create_table('site_revision',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=True),
    sa.Column('environment_name', sa.String(length=200), nullable=True),
    sa.Column('last_published', sa.DateTime(), nullable=True),
    sa.Column('local_build_dir', sa.String(length=200), nullable=True),
    sa.Column('static_files_dir', sa.String(length=200), nullable=True),
    sa.Column('hosting_type', sa.String(length=100), nullable=True),
    sa.Column('content_hash', sa.String(length=200), nullable=True),
    sa.Column('index_content', sa.Integer(), nullable=True),
    sa.Column('menu_content', sa.UnicodeText(), nullable=True),
    sa.Column('groups_content', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('_id', '_version')
    )
    op.create_index(op.f('ix_site_revision__id'), 'site_revision', ['_id'], unique=False)
    op.create_index(op.f('ix_site_revision__node_id'), 'site_revision', ['_node_id'], unique=False)
    op.create_index(op.f('ix_site_revision__timestamp'), 'site_revision', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_site_revision__version'), 'site_revision', ['_version'], unique=False)
    op.create_table('user',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_version', sa.Integer(), nullable=True),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('roles', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_user__id'), 'user', ['_id'], unique=False)
    op.create_index(op.f('ix_user__node_id'), 'user', ['_node_id'], unique=False)
    op.create_index(op.f('ix_user__timestamp'), 'user', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_user__version'), 'user', ['_version'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_revision',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('roles', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('_id', '_version')
    )
    op.create_index(op.f('ix_user_revision__id'), 'user_revision', ['_id'], unique=False)
    op.create_index(op.f('ix_user_revision__node_id'), 'user_revision', ['_node_id'], unique=False)
    op.create_index(op.f('ix_user_revision__timestamp'), 'user_revision', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_user_revision__version'), 'user_revision', ['_version'], unique=False)
    op.create_index(op.f('ix_user_revision_email'), 'user_revision', ['email'], unique=True)
    op.create_index(op.f('ix_user_revision_username'), 'user_revision', ['username'], unique=True)
    op.create_table('node',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_version', sa.Integer(), nullable=True),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('labels', sa.UnicodeText(), nullable=True),
    sa.Column('first_child', sa.String(length=200), nullable=True),
    sa.Column('layer_parents', sa.UnicodeText(), nullable=True),
    sa.Column('layer_children', sa.UnicodeText(), nullable=True),
    sa.Column('layer_next_node', sa.Integer(), nullable=True),
    sa.Column('layer_previous_node', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_node__id'), 'node', ['_id'], unique=False)
    op.create_index(op.f('ix_node__node_id'), 'node', ['_node_id'], unique=False)
    op.create_index(op.f('ix_node__timestamp'), 'node', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_node__version'), 'node', ['_version'], unique=False)
    op.create_index(op.f('ix_node_first_child'), 'node', ['first_child'], unique=False)
    op.create_index(op.f('ix_node_labels'), 'node', ['labels'], unique=False)
    op.create_table('node_revision',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_node_id', sa.Integer(), nullable=True),
    sa.Column('_hash', sa.String(length=140), nullable=True),
    sa.Column('_hash_chain', sa.String(length=140), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('_lock', sa.UnicodeText(), nullable=True),
    sa.Column('_state', sa.String(length=100), nullable=True),
    sa.Column('_perms', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('labels', sa.UnicodeText(), nullable=True),
    sa.Column('first_child', sa.String(length=200), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=False),
    sa.Column('layer_parents', sa.UnicodeText(), nullable=True),
    sa.Column('layer_children', sa.UnicodeText(), nullable=True),
    sa.Column('layer_next_node', sa.Integer(), nullable=True),
    sa.Column('layer_previous_node', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id', '_version')
    )
    op.create_index(op.f('ix_node_revision__id'), 'node_revision', ['_id'], unique=False)
    op.create_index(op.f('ix_node_revision__node_id'), 'node_revision', ['_node_id'], unique=False)
    op.create_index(op.f('ix_node_revision__timestamp'), 'node_revision', ['_timestamp'], unique=False)
    op.create_index(op.f('ix_node_revision__version'), 'node_revision', ['_version'], unique=False)
    op.create_index(op.f('ix_node_revision_first_child'), 'node_revision', ['first_child'], unique=False)
    op.create_index(op.f('ix_node_revision_labels'), 'node_revision', ['labels'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_revision_labels'), table_name='node_revision')
    op.drop_index(op.f('ix_node_revision_first_child'), table_name='node_revision')
    op.drop_index(op.f('ix_node_revision__version'), table_name='node_revision')
    op.drop_index(op.f('ix_node_revision__timestamp'), table_name='node_revision')
    op.drop_index(op.f('ix_node_revision__node_id'), table_name='node_revision')
    op.drop_index(op.f('ix_node_revision__id'), table_name='node_revision')
    op.drop_table('node_revision')
    op.drop_index(op.f('ix_node_labels'), table_name='node')
    op.drop_index(op.f('ix_node_first_child'), table_name='node')
    op.drop_index(op.f('ix_node__version'), table_name='node')
    op.drop_index(op.f('ix_node__timestamp'), table_name='node')
    op.drop_index(op.f('ix_node__node_id'), table_name='node')
    op.drop_index(op.f('ix_node__id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_user_revision_username'), table_name='user_revision')
    op.drop_index(op.f('ix_user_revision_email'), table_name='user_revision')
    op.drop_index(op.f('ix_user_revision__version'), table_name='user_revision')
    op.drop_index(op.f('ix_user_revision__timestamp'), table_name='user_revision')
    op.drop_index(op.f('ix_user_revision__node_id'), table_name='user_revision')
    op.drop_index(op.f('ix_user_revision__id'), table_name='user_revision')
    op.drop_table('user_revision')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user__version'), table_name='user')
    op.drop_index(op.f('ix_user__timestamp'), table_name='user')
    op.drop_index(op.f('ix_user__node_id'), table_name='user')
    op.drop_index(op.f('ix_user__id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_site_revision__version'), table_name='site_revision')
    op.drop_index(op.f('ix_site_revision__timestamp'), table_name='site_revision')
    op.drop_index(op.f('ix_site_revision__node_id'), table_name='site_revision')
    op.drop_index(op.f('ix_site_revision__id'), table_name='site_revision')
    op.drop_table('site_revision')
    op.drop_index(op.f('ix_site__version'), table_name='site')
    op.drop_index(op.f('ix_site__timestamp'), table_name='site')
    op.drop_index(op.f('ix_site__node_id'), table_name='site')
    op.drop_index(op.f('ix_site__id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_content_type_revision_name'), table_name='content_type_revision')
    op.drop_index(op.f('ix_content_type_revision__version'), table_name='content_type_revision')
    op.drop_index(op.f('ix_content_type_revision__timestamp'), table_name='content_type_revision')
    op.drop_index(op.f('ix_content_type_revision__node_id'), table_name='content_type_revision')
    op.drop_index(op.f('ix_content_type_revision__id'), table_name='content_type_revision')
    op.drop_table('content_type_revision')
    op.drop_index(op.f('ix_content_type_name'), table_name='content_type')
    op.drop_index(op.f('ix_content_type__version'), table_name='content_type')
    op.drop_index(op.f('ix_content_type__timestamp'), table_name='content_type')
    op.drop_index(op.f('ix_content_type__node_id'), table_name='content_type')
    op.drop_index(op.f('ix_content_type__id'), table_name='content_type')
    op.drop_table('content_type')
    op.drop_index(op.f('ix_article_revision__version'), table_name='article_revision')
    op.drop_index(op.f('ix_article_revision__timestamp'), table_name='article_revision')
    op.drop_index(op.f('ix_article_revision__node_id'), table_name='article_revision')
    op.drop_index(op.f('ix_article_revision__id'), table_name='article_revision')
    op.drop_table('article_revision')
    op.drop_index(op.f('ix_article__version'), table_name='article')
    op.drop_index(op.f('ix_article__timestamp'), table_name='article')
    op.drop_index(op.f('ix_article__node_id'), table_name='article')
    op.drop_index(op.f('ix_article__id'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
